In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

# Cargar el archivo principal
# Usamos sep=';' porque los datos están separados por punto y coma
df_banco = pd.read_csv('bank-additional.csv', sep=';')

# Mostrar las primeras 5 filas para verificar que se cargó bien
print(df_banco.head())

# Ver información básica de las columnas y tipos de datos
print(df_banco.info())

   Unnamed: 0   age        job  marital    education  default  housing  loan  \
0           0   NaN  housemaid  MARRIED     basic.4y      0.0      0.0   0.0
1           1  57.0   services  MARRIED  high.school      NaN      0.0   0.0
2           2  37.0   services  MARRIED  high.school      0.0      1.0   0.0
3           3  40.0     admin.  MARRIED     basic.6y      0.0      0.0   0.0
4           4  56.0   services  MARRIED  high.school      0.0      0.0   1.0

     contact  duration  ...  emp.var.rate  cons.price.idx  cons.conf.idx  \
0  telephone       261  ...           1.1          93,994          -36,4
1  telephone       149  ...           1.1          93,994          -36,4
2  telephone       226  ...           1.1          93,994          -36,4
3  telephone       151  ...           1.1          93,994          -36,4
4  telephone       307  ...           1.1          93,994          -36,4

  euribor3m  nr.employed   y       date latitude longitude  \
0     4,857         5191  no  02-ago-19   41.495   -71.233
1       NaN         5191  no  14-sep-16   34.601   -83.923
2     4,857         5191  no  15-feb-19   34.939   -94.847
3       NaN         5191  no  29-nov-15   49.041   -70.308
4       NaN         5191  no  29-ene-17   38.033  -104.463

                                    id_
0  089b39d8-e4d0-461b-87d4-814d71e0e079
1  e9d37224-cb6f-4942-98d7-46672963d097
2  3f9f49b5-e410-4948-bf6e-f9244f04918b
3  9991fafb-4447-451a-8be2-b0df6098d13e
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb

[5 rows x 24 columns]
<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB
None

In [12]:
import pandas as pd

# Cargamos el archivo usando el separador ';'
# Usamos index_col=0 porque el archivo empieza con un punto y coma vacío (la columna de índices)
df_2012 = pd.read_csv('customer-details-2012.csv', sep=';', index_col=0)

# Mostramos el resultado
print("¡Archivo cargado con éxito!")
print(f"Dimensiones de la tabla: {df_2012.shape}") # (filas, columnas)
print("\nPrimeras filas:")
print(df_2012.head())

¡Archivo cargado con éxito!
Dimensiones de la tabla: (20115, 6)

Primeras filas:
   Income  Kidhome  Teenhome          Dt_Customer  NumWebVisitsMonth  \
0  161770        1         0  2012-04-04 00:00:00                 29
1   85477        1         1  2012-12-30 00:00:00                  7
2  147233        1         1  2012-02-02 00:00:00                  5
3  121393        1         2  2012-12-21 00:00:00                 29
4   63164        1         2  2012-06-20 00:00:00                 20

                                     ID
0  089b39d8-e4d0-461b-87d4-814d71e0e079
1  e9d37224-cb6f-4942-98d7-46672963d097
2  3f9f49b5-e410-4948-bf6e-f9244f04918b
3  9991fafb-4447-451a-8be2-b0df6098d13e
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [13]:
import pandas as pd

# 1. Cargamos el nuevo archivo de 2013
df_2013 = pd.read_csv('customer-details-2013.csv', sep=';', index_col=0)

# 2. Cargamos el de 2012 (asegúrate de haberlo cargado antes)
df_2012 = pd.read_csv('customer-details-2012.csv', sep=';', index_col=0)

# 3. Los unimos en una sola tabla llamada 'df_clientes'
# Esto pone los datos de 2013 justo debajo de los de 2012
df_clientes = pd.concat([df_2012, df_2013], ignore_index=True)

print("--- PROCESO COMPLETADO ---")
print(f"Registros en 2012: {len(df_2012)}")
print(f"Registros en 2013: {len(df_2013)}")
print(f"Total en la tabla combinada: {len(df_clientes)}")
print("\nVistazo a los datos combinados:")
print(df_clientes.head())

--- PROCESO COMPLETADO ---
Registros en 2012: 20115
Registros en 2013: 8965
Total en la tabla combinada: 29080

Vistazo a los datos combinados:
   Income  Kidhome  Teenhome          Dt_Customer  NumWebVisitsMonth  \
0  161770        1         0  2012-04-04 00:00:00                 29
1   85477        1         1  2012-12-30 00:00:00                  7
2  147233        1         1  2012-02-02 00:00:00                  5
3  121393        1         2  2012-12-21 00:00:00                 29
4   63164        1         2  2012-06-20 00:00:00                 20

                                     ID
0  089b39d8-e4d0-461b-87d4-814d71e0e079
1  e9d37224-cb6f-4942-98d7-46672963d097
2  3f9f49b5-e410-4948-bf6e-f9244f04918b
3  9991fafb-4447-451a-8be2-b0df6098d13e
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [14]:
import pandas as pd

# 1. Cargamos el archivo de 2014
df_2014 = pd.read_csv('customer-details-2014.csv', sep=';', index_col=0)

# 2. Cargamos los anteriores (asegúrate de que los nombres sean correctos)
df_2012 = pd.read_csv('customer-details-2012.csv', sep=';', index_col=0)
df_2013 = pd.read_csv('customer-details-2013.csv', sep=';', index_col=0)

# 3. Unimos los tres años en una sola tabla de clientes
df_clientes = pd.concat([df_2012, df_2013, df_2014], ignore_index=True)

# 4. Cargamos también la tabla del banco para tenerla lista
df_banco = pd.read_csv('bank-additional.csv', sep=';', index_col=0)

print("--- TODO CARGADO Y UNIFICADO ---")
print(f"Total de registros de clientes (2012+2013+2014): {len(df_clientes)}")
print(f"Total de registros en la tabla del banco: {len(df_banco)}")

--- TODO CARGADO Y UNIFICADO ---
Total de registros de clientes (2012+2013+2014): 43170
Total de registros en la tabla del banco: 43000

In [15]:
# 1. Realizamos la unión (merge) de las dos tablas
# Usamos 'left_on' para la columna del banco y 'right_on' para la de clientes
df_final = pd.merge(df_banco, df_clientes, left_on='id_', right_on='ID')

# 2. Como ahora tenemos dos columnas de ID que son iguales, borramos una para no repetir
df_final = df_final.drop(columns=['ID'])

# 3. Revisamos el resultado final
print("--- UNIÓN COMPLETADA ---")
print(f"Ahora tienes una tabla maestra con {df_final.shape[0]} filas y {df_final.shape[1]} columnas.")
print("\nPrimeras 5 filas de tu nueva tabla unificada:")
display(df_final.head())

# 4. Tip extra: ¿Cuántos datos nos faltan ahora?
print("\nResumen de valores vacíos en la tabla final:")
print(df_final.isnull().sum())

--- UNIÓN COMPLETADA ---
Ahora tienes una tabla maestra con 43000 filas y 28 columnas.

Primeras 5 filas de tu nueva tabla unificada:

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,no,02-ago-19,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04 00:00:00,29
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,no,14-sep-16,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30 00:00:00,7
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,no,15-feb-19,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02 00:00:00,5
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,no,29-nov-15,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21 00:00:00,29
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,no,29-ene-17,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20 00:00:00,20

Resumen de valores vacíos en la tabla final:
age                  5120
job                   345
marital                85
education            1807
default              8981
housing              1026
loan                 1026
contact                 0
duration                0
campaign                0
pdays                   0
previous                0
poutcome                0
emp.var.rate            0
cons.price.idx        471
cons.conf.idx           0
euribor3m            9256
nr.employed             0
y                       0
date                  248
latitude                0
longitude               0
id_                     0
Income                  0
Kidhome                 0
Teenhome                0
Dt_Customer             0
NumWebVisitsMonth       0
dtype: int64

In [16]:
# 1. Identificar cuántos valores nulos hay por columna
print("Valores nulos antes de limpiar:")
print(df_final.isnull().sum())

# 2. LIMPIEZA DE 'Income' (Ingresos)
# Vamos a rellenar los ingresos vacíos con la MEDIANA (el valor central) 
# para que los valores extremos no afecten el análisis.
mediana_ingresos = df_final['Income'].median()
df_final['Income'] = df_final['Income'].fillna(mediana_ingresos)

# 3. LIMPIEZA DE 'age' (Edad)
# Para la edad, usaremos el promedio (mean) y lo convertiremos a número entero
promedio_edad = df_final['age'].mean()
df_final['age'] = df_final['age'].fillna(promedio_edad).astype(int)

# 4. NORMALIZAR TEXTO (Columna 'job' y 'marital')
# Pasamos todo a minúsculas para que 'MARRIED' y 'married' sean lo mismo
df_final['job'] = df_final['job'].str.lower()
df_final['marital'] = df_final['marital'].str.lower()

# 5. CONVERTIR FECHAS
# Transformamos 'Dt_Customer' a un formato de fecha real que Python entienda
df_final['Dt_Customer'] = pd.to_datetime(df_final['Dt_Customer'])

print("\n--- ¡LIMPIEZA COMPLETADA! ---")
print(f"Nulos restantes en Income: {df_final['Income'].isnull().sum()}")
print(f"Nulos restantes en age: {df_final['age'].isnull().sum()}")
display(df_final.head())

Valores nulos antes de limpiar:
age                  5120
job                   345
marital                85
education            1807
default              8981
housing              1026
loan                 1026
contact                 0
duration                0
campaign                0
pdays                   0
previous                0
poutcome                0
emp.var.rate            0
cons.price.idx        471
cons.conf.idx           0
euribor3m            9256
nr.employed             0
y                       0
date                  248
latitude                0
longitude               0
id_                     0
Income                  0
Kidhome                 0
Teenhome                0
Dt_Customer             0
NumWebVisitsMonth       0
dtype: int64

--- ¡LIMPIEZA COMPLETADA! ---
Nulos restantes en Income: 0
Nulos restantes en age: 0

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,39,housemaid,married,basic.4y,0.0,0.0,0.0,telephone,261,1,...,no,02-ago-19,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57,services,married,high.school,NaN,0.0,0.0,telephone,149,1,...,no,14-sep-16,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37,services,married,high.school,0.0,1.0,0.0,telephone,226,1,...,no,15-feb-19,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40,admin.,married,basic.6y,0.0,0.0,0.0,telephone,151,1,...,no,29-nov-15,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56,services,married,high.school,0.0,0.0,1.0,telephone,307,1,...,no,29-ene-17,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

In [17]:
import pandas as pd
import numpy as np

# --- 1. CARGA DE DATOS (Raw Data) ---
# Cargamos el banco y los 3 archivos de clientes
df_bank = pd.read_csv('bank-additional.csv', sep=';', index_col=0)
df_2012 = pd.read_csv('customer-details-2012.csv', sep=';', index_col=0)
df_2013 = pd.read_csv('customer-details-2013.csv', sep=';', index_col=0)
df_2014 = pd.read_csv('customer-details-2014.csv', sep=';', index_col=0)

# --- 2. CONCATENACIÓN Y UNIÓN (Merge) ---
# Unimos los clientes en un solo bloque
df_customers = pd.concat([df_2012, df_2013, df_2014], ignore_index=True)

# Unión maestra: usamos 'id_' del banco e 'ID' de clientes
df_raw = pd.merge(df_bank, df_customers, left_on='id_', right_on='ID', how='inner')

# --- 3. LIMPIEZA DE DATOS ---
# A. Eliminar duplicados si existen
df_clean = df_raw.drop_duplicates()

# B. Eliminar columnas redundantes (ID repetido)
df_clean = df_clean.drop(columns=['ID'])

# C. Gestión de Nulos (Imputación)
# - Ingresos: Usamos la mediana (más robusta frente a valores extremos)
df_clean['Income'] = df_clean['Income'].fillna(df_clean['Income'].median())
# - Edad: Usamos la media y convertimos a entero
df_clean['age'] = df_clean['age'].fillna(df_clean['age'].mean()).astype(int)

# D. Estandarización de texto
# Ponemos profesiones y estado civil en minúsculas y quitamos puntos finales
df_clean['job'] = df_clean['job'].str.lower().str.replace('.', '', regex=False)
df_clean['education'] = df_clean['education'].str.replace('.', '_', regex=False)

# E. Conversión de tipos
df_clean['Dt_Customer'] = pd.to_datetime(df_clean['Dt_Customer'])

# F. Feature Engineering (Creación de nuevas variables útiles para el análisis)
# Creamos una columna que sume niños y adolescentes para saber el total de menores en casa
df_clean['total_minors'] = df_clean['Kidhome'] + df_clean['Teenhome']

# --- 4. GUARDAR RESULTADOS ---
# El proyecto pide una carpeta de datos procesados. Guardamos el CSV limpio.
df_clean.to_csv('datos_limpios.csv', index=False)

print("¡Proceso de limpieza finalizado!")
print(f"Registros originales: {len(df_raw)} | Registros tras limpieza: {len(df_clean)}")
print(f"Nulos totales detectados: {df_clean.isnull().sum().sum()}")

¡Proceso de limpieza finalizado!
Registros originales: 43000 | Registros tras limpieza: 43000
Nulos totales detectados: 23245

In [18]:
# --- 1. ESTADÍSTICAS GENERALES ---
# El método .describe() nos da media, mediana (50%), desviación estándar, etc.
print("--- Resumen Estadístico de Variables Numéricas ---")
stats_numericas = df_final[['age', 'Income', 'campaign', 'duration', 'NumWebVisitsMonth']].describe()
display(stats_numericas)

# --- 2. ANÁLISIS DE LA VARIABLE OBJETIVO (Tasa de Éxito) ---
# ¿Qué porcentaje de clientes aceptó el producto ('yes')?
print("\n--- Tasa de suscripción (Variable 'y') ---")
tasa_exito = df_final['y'].value_counts(normalize=True) * 100
print(tasa_exito)

# --- 3. ANÁLISIS POR SEGMENTOS (Agrupamientos) ---
# A. ¿Qué profesiones tienen el ingreso promedio más alto?
print("\n--- Top 5 Profesiones por Ingreso Promedio ---")
ingreso_por_job = df_final.groupby('job')['Income'].mean().sort_values(ascending=False)
print(ingreso_por_job.head())

# B. ¿Influye el estado civil en la aceptación del producto?
print("\n--- Tasa de éxito por Estado Civil ---")
exito_marital = df_final.groupby('marital')['y'].value_counts(normalize=True).unstack()['yes'] * 100
print(exito_marital.sort_values(ascending=False))

# --- 4. ANÁLISIS DE CORRELACIÓN ---
# Esto ayuda a ver si hay relación entre variables (ej. ¿más ingresos = más visitas web?)
print("\n--- Matriz de Correlación (relación con Income) ---")
# Seleccionamos solo las columnas numéricas para evitar errores
columnas_num = df_final.select_dtypes(include=['number'])
correlacion = columnas_num.corr()
# Mostramos solo cómo se relaciona todo con el ingreso
print(correlacion['Income'].sort_values(ascending=False))

--- Resumen Estadístico de Variables Numéricas ---

,age,Income,campaign,duration,NumWebVisitsMonth
count,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,39.860767,93241.200070,2.567233,257.739279,16.589698
std,9.801940,50498.316182,2.772294,258.666033,9.239205
min,17.000000,5841.000000,1.000000,0.000000,1.000000
25%,33.000000,49610.000000,1.000000,102.000000,9.000000
50%,39.000000,93050.500000,2.000000,179.000000,17.000000
75%,46.000000,136744.500000,3.000000,319.000000,25.000000
max,98.000000,180802.000000,56.000000,4918.000000,32.000000

--- Tasa de suscripción (Variable 'y') ---
y
no     88.734884
yes    11.265116
Name: proportion, dtype: float64

--- Top 5 Profesiones por Ingreso Promedio ---
job
housemaid        97263.776492
self-employed    93804.711216
technician       93652.971819
entrepreneur     93581.474376
student          93547.688815
Name: Income, dtype: float64

--- Tasa de éxito por Estado Civil ---
marital
single      13.928129
married     10.211931
divorced    10.184993
Name: yes, dtype: float64

--- Matriz de Correlación (relación con Income) ---
Income               1.000000
Teenhome             0.006480
pdays                0.004092
loan                 0.003440
NumWebVisitsMonth    0.002500
default              0.002141
age                  0.001728
Kidhome              0.001350
housing              0.000470
longitude            0.000360
duration            -0.002761
previous            -0.003207
campaign            -0.003736
latitude            -0.004433
emp.var.rate        -0.008640
Name: Income, dtype: float64

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Preparación de los datos para la visualización
# Calculamos la tasa de éxito (porcentaje de 'yes') por cada tipo de trabajo
# Usamos normalize=True para obtener proporciones y multiplicamos por 100
tasa_exito_job = df_clean.groupby('job')['y'].value_counts(normalize=True).unstack()['yes'] * 100
tasa_exito_job = tasa_exito_job.sort_values(ascending=False)

# 2. Configuración del estilo del gráfico
sns.set_theme(style="whitegrid")
plt.figure(figsize=(12, 6))

# 3. Creación del gráfico de barras
sns.barplot(x=tasa_exito_job.index, y=tasa_exito_job.values, palette='viridis')

# 4. Personalización y etiquetas
plt.title('Tasa de Éxito de Suscripción por Profesión (%)', fontsize=16, fontweight='bold')
plt.xlabel('Profesión', fontsize=12)
plt.ylabel('Éxito en Suscripción (%)', fontsize=12)
plt.xticks(rotation=45) # Rotamos las etiquetas para que sean legibles

# 5. Añadir el valor exacto sobre cada barra para mayor precisión
for i, value in enumerate(tasa_exito_job.values):
    plt.text(i, value + 0.5, f'{value:.1f}%', ha='center', fontsize=10)

plt.tight_layout()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'